### ISSUE TITLE
Unexpected errors in alternative paths for observation Heart Rate

### ISSUE THREAD

**Issue by af-pwo** [ehrbase/fhir-bridge#212] opened 2021-02-18 16:47 UTC
## Test Case/s To Reproduce Issue
Alternative Flows Observation Heart Rate

```
# path to test case
tests/robot/OBSERVATION/01_create.robot
```

```
# robot command to execute related test case(s) in your terminal/console

robot -d results/ -L TRACE -i heart-rateAND212 robot

# by test case name (wildcards possible)


075 Create Heart Rate loinc period
076 Create Heart Rate loinc period_2
078 Create Heart Rate snomed period
079 Create Heart Rate snomed period_2


## Actual Result

422

No Java Stack Trace

{'issue': [{'code': 'processing',
                     'diagnostics': 'vs-1: if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day [($this as dateTime).toString().length() >= 8]',
                     'location': ['Observation.effective.ofType(Period)',
                                  'Line 1, Col 592'],
                     'severity': 'error'}]


## Expected Result

200

**Comment by ErikTute** [comment] 2021-05-05 09:42
@ppazos I had nothing to do with robot tests so far. Can you take care of this issue and #281? (I guess learning what robot tests are, why we are doing it and how I can use them would need more time than fixing these two issues)

**Comment by ppazos** [comment] 2021-05-05 14:07
@ErikTute robot is used for testing, the issue is about the result obtained from the test, something that should be fixed in code. If you want to replicate the test but don't want to use robot, you can just grab the resource used in the test and test manually. On the other hand, I had been asked explicitly to not touch the FHIR bridge code. Please as Birger if you need support from our side.

**Comment by ErikTute** [comment] 2021-05-10 15:06
@ppazos  @birgerhaarbrandt @SevKohler 
Hi, I honestly wanted to and started to figure out whats wrong here, but again, I am a bad choice for this task:
- "grab the resource used and do it manually" does not help if you don't know shit about robot tests. I still have to understand whats happening to reproduce it, so I have to find my stuff in 432 lines of code I never saw before, just to reproduce the problem.
- I assume that it's some unsupported value for Observation.effective which is the problem? This is not processed in the specific heart rate mapping but in the generic stuff, I think ObservationToObservation which I never touched and probably should not touch.

So please someone just redeem my little soul.

**Comment by birgerhaarbrandt** [comment] 2021-05-11 07:11
@ppazos please address the issue directly and have a brief review with Severin afterwards. thx

**Comment by ppazos** [comment] 2021-05-12 02:48
# 075/078 fails on:

```
	"effectivePeriod": {
		"start": "1999-07-02"
	}
```

From create-heart-rate-loinc-period.json

The profile rule is: "vs-1: 'if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day' failed"

The rule description doesn't seem to match what is being checked:

```
($this as dateTime).toString().length() >= 8
```

From: https://simplifier.net/forschungsnetzcovid-19/heartrate


# 076/079 fails on:

```
"effectivePeriod": {
   "start": "1999-07-02",
   "end": "1997-07-02"
}
```

From create-heart-rate-loinc-period_2.json

The profile rules that fail are:

1. "vs-1: 'if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day' failed"
2. "per-1: 'If present, start SHALL have a lower value than end' failed"

Rule 1 description doesn't seem to match what is being checked:

```
($this as dateTime).toString().length() >= 8
```

From: https://simplifier.net/forschungsnetzcovid-19/heartrate

Rule 2 is part of the Period definition (https://www.hl7.org/fhir/period.profile.json.html), surely caused by a typo in the data set.

# Solution: the vs-1 rule should be fixed in the profile, I'll contact Julian.

UPDATE: Julian confirmed this is an issue in the profile and it will be updated in the next couple of days.

**Comment by ppazos** [comment] 2021-05-19 04:26
Updated the heart rate profile, this solved the initial issue but generated other issues with robot tests.

I'm reviewing the tests that are failing and solving them.

**Comment by SevKohler** [comment] 2021-06-21 11:56
@ppazos is it done ?

**Comment by ppazos** [comment] 2021-06-21 18:02
@SevKohler it seems you merged the fix https://github.com/ehrbase/fhir-bridge/pull/335 so I guess it's done.

**Closed as completed by ppazos** 2021-06-21 18:02 UTC
Labels: bug
